# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200110_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
