# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20200110_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bvps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='esp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fixedassets',
            field=models.FloatField(blank=True, db_column='fixedAssets', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gpr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='holders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='liquidassets',
            field=models.FloatField(blank=True, db_column='liquidAssets', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='npr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='perundp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reserved',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reservedpershare',
            field=models.FloatField(blank=True, db_column='reservedPerShare', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='timetomarket',
            field=models.TextField(blank=True, db_column='timeToMarket', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='totalassets',
            field=models.FloatField(blank=True, db_column='totalAssets', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='undp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
